apiVersion: v1
kind: Service
metadata:
  name: calculator-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: simple-calculator
  ports:
    - port: 80          # Cluster IP port
      targetPort: 3000  # Pod port
      nodePort: 30172   # External port to access from nodes

