apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-calculator
  template:
    metadata:
      labels:
        app: simple-calculator
    spec:
      containers:
      - name: calculator
        image: your-dockerhub-username/simple-calculator:REPLACE_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
